
[[constraint]]
  branch = "master"
  name = "github.com/spf13/cobra"

[[constraint]]
  name = "k8s.io/helm"
  version = "2.8.2"

[[constraint]]
  name = "github.com/spf13/afero"
  version = "1.0.2"

[[override]]
  name = "github.com/spf13/cast"
  version = "1.2.0"

