apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "foobar.fullname" . }}
  labels:
    app: {{ template "foobar.fullname" . }}
    chart: {{ template "foobar.chartref" . }}
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
data:
