apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "<% .Chart.Name %>.fullname" . }}
  labels:
    app: {{ template "<% .Chart.Name %>.name" . }}
    chart: {{ template "<% .Chart.Name %>.chartref" . }}
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
spec:
  template:
    metadata:
      labels:
        app: {{ template "<% .Chart.Name %>.name" . }}
        release: {{ .Release.Name | quote }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http
          containerPort: 80
        resources:
{{ toYaml .Values.resources | indent 10 }}
